// import "./globals.css";
// import Nav from "./ui/Nav";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="antialiased" style={{ fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 300 }}>
//         <Nav />
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Nav from "./ui/Nav";

export const metadata = {
  title: "Intrinsic",
  description: "Anytime. Anywhere.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-light" style={{ fontFamily: '"Montserrat", sans-serif' }}>
        <Nav />
        {children}
      </body>
    </html>
  );
}